### PR TITLE
Fix: ReportUsersWalletAddresses isn't retained so changes aren't tracked (for debugging purposes)

### LINKED ISSUE #5224: ReportUsersWalletAddresses isn't retained so changes aren't tracked (for debugging purposes)

### PR DESCRIPTION
**Pull request by hboon**
Closes #5224

### CODE REVIEW

File: AlphaWallet/AppCoordinator.swift [hunk 1]
```diff
@@ -13,6 +13,8 @@ class AppCoordinator: NSObject, Coordinator {
     private let assetDefinitionStore = AssetDefinitionStore()
     private let window: UIWindow
     private var appTracker = AppTracker()
+    //TODO rename and replace type? Not Initializer but similar as of writing
```
Comment (hboon) [inline AlphaWallet/AppCoordinator.swift:16]: Have a TODO here; wanted to keep the PR small

**Review by oa-s — APPROVED** [review]
