### PR TITLE
Crash with large wallet #2341

### LINKED ISSUE #1334: Reproduce Realm database growing to enormous size
10s of GBs on hboon's simulator in laptop. This might have been due to a debugging set up and might have already been fixed earlier. Report back if we can reproduce it @James-Sangalli

### LINKED ISSUE #2340: Slow with large wallet
From Sunil https://github.com/AlphaWallet/alpha-wallet-ios/issues/2293#issue-746194844:

> 2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872

### LINKED ISSUE #2341: Crash with large wallet
From Sunil https://github.com/AlphaWallet/alpha-wallet-ios/issues/2293#issue-746194844:

> 2. Know it is a test build, but was slow especially for wallets with a large number of tokens and transactions. Crashed often, you can use to test this 0x26aaD4D82f6c9FA6E34D8c1067429C986A055872

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2341, Closes #2340, Closes #1334

### CODE REVIEW

File: AlphaWallet/Transactions/Storage/TransactionsStorage.swift [hunk 1]
```diff
@@ -75,8 +75,7 @@ class TransactionsStorage {
             if each.isERC20Interaction {
                 return true
             } else {
-                let erc20TransactionExists = realm.objects(Transaction.self).filter("isERC20Interaction == true").contains { each.id == $0.id }
-                return !erc20TransactionExists
+                return realm.object(ofType: Transaction.self, forPrimaryKey: each.primaryKey) != nil
```
Comment (hboon) [inline AlphaWallet/Transactions/Storage/TransactionsStorage.swift:78]: I think this should be == nil instead?

File: AlphaWallet/Core/Initializers/MigrationInitializer.swift [hunk 2]
```diff
@@ -16,7 +16,10 @@ class MigrationInitializer: Initializer {
 
     func perform() {
         config.schemaVersion = 7
-        config.migrationBlock = { migration, oldSchemaVersion in
+        //NOTE: use [weak self] to avaid memory leak
```
Comment (hboon) [inline AlphaWallet/Core/Initializers/MigrationInitializer.swift:19]: Good catch! Can you help pull move into a separate PR?

**Review by hboon — CHANGES_REQUESTED** [review]

**Review by James-Sangalli — APPROVED** [review]
