### PR TITLE
Fix add a custom token in Add / Hide Tokens screen does not show the token in the first list #1968

### LINKED ISSUE #1968: Fix add a custom token in Add / Hide Tokens screen does not show the token in the first list
Verify if true first.

This might happen because we disabled refreshing:

```
    private func handleTokenCollectionUpdates() {
        //no-op because we do not want to refresh this screen as it's a bad user experience if the tokens reload while the user is toggling their visibility
    }
```

This was disabled because if the list of tokens refreshes while the user changes the position of the token or switch between show/hiding them, the changes will be lost.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1968

### CODE REVIEW

File: AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift [hunk 1]
```diff
@@ -19,10 +19,10 @@ private enum AddHideTokenSections: Int {
     }
 }
 
-struct AddHideTokensViewModel {
+class AddHideTokensViewModel {
     private let sections: [AddHideTokenSections] = [.displayedTokens, .hiddenTokens]
     private let filterTokensCoordinator: FilterTokensCoordinator
-    private var tokens: [TokenObject]
+    var tokens: [TokenObject]
```
Comment (hboon) [inline AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:25]: Looks like `tokens` can still be private

File: AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift [hunk 2]
```diff
@@ -19,10 +19,10 @@ private enum AddHideTokenSections: Int {
     }
 }
 
-struct AddHideTokensViewModel {
+class AddHideTokensViewModel {
```
Comment (hboon) [inline AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:22]: Why do you change it from a struct to a class?

File: AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift (hunk 1 above)
Comment (vladyslav-iosdev) [reply AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:25]: ooh, yep you right.

File: AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift (hunk 2 above)
Comment (hboon) [reply AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:22]: If there's a special reason, can you leave a comment like in `TokensViewModel`? Otherwise, it's easy in the future to change it back and the code only breaks silently.

Comment (vladyslav-iosdev) [reply AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:22]: i changed it to class because we need to refresh view model in apply updates in only one place, then to not to update separately coordinator and view controller.

Comment (vladyslav-iosdev) [reply AlphaWallet/Tokens/ViewModels/AddHideTokensViewModel.swift:22]: ok, np.
