### PR TITLE
Suppose to fix crash when update nft balance #4429

### LINKED ISSUE #4429: Fix crash when update nft balance

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4429

### CODE REVIEW

File: AlphaWallet/Tokens/Types/TokensDataStore.swift [hunk 1]
```diff
@@ -406,12 +406,11 @@ enum TokenUpdateAction {
                 }
             }
 
-            result = true
-
-            realm.delete(tokenObject.balance)
-            tokenObject.balance.append(objectsIn: newBalance)
+            tokenObject.balance.removeAll()
```
Comment (hboon) [inline AlphaWallet/Tokens/Types/TokensDataStore.swift:409]: Do we still need `result = true` ?

**Review by hboon — COMMENTED** [review]
And don't forget to fix the commit message :)

File: AlphaWallet/Tokens/Types/TokensDataStore.swift (hunk 1 above)
Comment (oa-s) [reply AlphaWallet/Tokens/Types/TokensDataStore.swift:409]: for now yes, but i got another non merged pr, where it not needed
