### PR TITLE
Fix displaying swap amount on confirmation popup #6076

### LINKED ISSUE #6076: Fix displaying swap amount on confirmation popup

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6076

### CODE REVIEW

**Comment by oa-s** [comment]
| Before PR | After PR |
| -------- | -------- |
|  |  |

File: AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SwapTransactionViewModel.swift [hunk 1]
```diff
@@ -72,13 +72,15 @@ extension TransactionConfirmationViewModel {
                     return .init(title: .normal(configurationTitle), headerName: headerName, details: gasFee, configuration: configuration)
                 }
             case .from:
-                let amount = EtherNumberFormatter.short.string(from: BigInt(fromAmount), decimals: fromToken.decimals)
-                let symbol = fromToken.symbol
-                return .init(title: .normal("\(amount) \(symbol)"), headerName: headerName, configuration: configuration)
+                let doubleAmount = (Decimal(bigInt: BigInt(fromAmount), decimals: fromToken.decimals) ?? .zero).doubleValue
+                let amount = NumberFormatter.shortCrypto.string(double: doubleAmount, minimumFractionDigits: 4, maximumFractionDigits: 8)
```
Comment (hboon) [inline AlphaWallet/Transfer/ViewModels/TransactionConfirmation/SwapTransactionViewModel.swift:76]: I think we might have the `4` as a constant somewhere. If we haven't, we should (8 too).

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Buzz to check #6063 after this is merge
