### PR TITLE
WalletConnect using mobile linking crashes if the chain is disabled #2609

### LINKED ISSUE #2609: WalletConnect using mobile linking crashes if the chain is disabled
1. Disable Ethereum mainnet
2. Dapp Browser tab (Maybe mobile Safari will work too)
3. Visit https://example.walletconnect.org
4. Tap "Connect to WalletConnect"
5. Tap "3"
6. Tap "AlphaWallet"

Expected:

7. It works

Observed:

7. Crashes

I think the if we change step 2 to scan a QR code, the connection attempt gets silently ignored.

If we can figure out the chain, can we make this display an error message? Like "\(server.name) is disabled. Please enable it in Settings > Select Active Networks". As a follow up PR, we can make it better like improve the message and have a button to open that screen.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2609

### CODE REVIEW

File: AlphaWallet/Settings/Types/Constants.swift [hunk 1]
```diff
@@ -58,6 +58,7 @@ public struct Constants {
     public static let burnAddressString = "0x000000000000000000000000000000000000dEaD"
     static let nullAddress = AlphaWallet.Address(uncheckedAgainstNullAddress: "0x0000000000000000000000000000000000000000")!
     static let nativeCryptoAddressInDatabase = nullAddress
+    static let ensContractOnMainnet = nullAddress
```
Comment (vladyslav-iosdev) [inline AlphaWallet/Settings/Types/Constants.swift:61]: @hboon can u please check this one, it was mised in prev PR.

Comment (hboon) [reply AlphaWallet/Settings/Types/Constants.swift]: Got it in. Thanks

**Review by hboon — APPROVED** [review]
