### PR TITLE
Filter activities to avoid duplicate activity id, to avoid crash #5104

### LINKED ISSUE #5104: Filter activities to avoid duplicate activity id, to avoid crash

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5104

### CODE REVIEW

File: AlphaWallet/Activities/ActivitiesService.swift [hunk 1]
```diff
@@ -188,7 +188,9 @@ class ActivitiesService: NSObject, ActivitiesServiceType {
         //NOTE: here is a lot of calculations, `contractsAndCards` could reach up of 1000 items, as well as recentEvents could reach 1000.Simply it call inner function 1 000 000 times
         for (eachContract, eachServer, card, interpolatedFilter) in contractsAndCards {
             let activities = getActivities(forTokenContract: eachContract, server: eachServer, card: card, interpolatedFilter: interpolatedFilter)
-            activitiesAndTokens.append(contentsOf: activities)
+            //NOTE: filter activities to avoid: `Fatal error: Duplicate values for key: '<id>'`
+            let filteredActivities = activities.filter { data in !activitiesAndTokens.contains(where: { $0.activity.id == data.activity.id }) }
```
Comment (hboon) [inline AlphaWallet/Activities/ActivitiesService.swift:192]: Defensive is good. But why is it duplicated in the first place?

Comment (oa-s) [reply AlphaWallet/Activities/ActivitiesService.swift:192]: have no idea, it happened for me a few times on apps launch, also have facing this at firebase console

**Review by hboon — APPROVED** [review]
