### PR TITLE
set valid token balance when importing nonfungible token #4937

### LINKED ISSUE #4937: "Impossible To Build Configuration"
Refer https://github.com/AlphaWallet/alpha-wallet-ios/issues/4888#issuecomment-1175351309

@Hoanib would you help to describe how to reproduce this?

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #4937

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s Does this only fix it for ERC-1155? Do we have the same problem for ERC-721?

**Comment by oa-s** [comment]
nope it should be for all non fungible types

File: AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift [hunk 1]
```diff
@@ -314,20 +325,28 @@ class NewTokenViewController: UIViewController {
...
         let decimals = Int(decimalsTextField.value) ?? 0
         guard let tokenType = self.tokenType else { return }
-        //TODO looks wrong to mention ERC875TokenBalance specifically
-        var balance: [String] = viewModel.erc875TokenBalance
+
+        var nonFungibleBalance: NonFungibleBalance
+        switch tokenType {
+        case .erc875:
+            if let balance = viewModel.nonFungibleBalance {
+                nonFungibleBalance = balance.rawValue.isEmpty ? .erc875(["0"]) : balance
```
Comment (hboon) [inline AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift:333]: Should this be `.erc875([])` or `.erc875([0])`? Ditto for 2 lines below this.

File: AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift [hunk 2]
```diff
@@ -314,20 +325,28 @@ class NewTokenViewController: UIViewController {
...
+            } else {
+                nonFungibleBalance = .erc875(["0"])
+            }
+        case .nativeCryptocurrency, .erc20, .erc721, .erc1155:
+            nonFungibleBalance = viewModel.nonFungibleBalance ?? .balance([])
```
Comment (hboon) [inline AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift:338]: This one's an impossible path right? Shall we do an `assertImpossibleCodePath(message:)`? 

(we'll change the implementation for `assertImpossibleCodePath(message:)` and `assertImpossibleCodePath()` to use `preconditionFailure(_:)` instead of `assert(Bool,String)` in the future)

**Review by hboon — APPROVED** [review]
Looks OK. Assume you tested. A little hard to predict what would happen without stepping through it (which I didn't), unfortunately.

File: AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift (hunk 1 above)
Comment (oa-s) [reply AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift:333]: actually i don't know, previous implementation setting initial value as "0", if array is empty

File: AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift (hunk 2 above)
Comment (oa-s) [reply AlphaWallet/Tokens/ViewControllers/NewTokenViewController.swift:338]: i guess for that we need to tweak ErcToken model, because nonFungible balance isn't optional, and in any case balance need to be calculated
