### PR TITLE
Fix crash when displaying swap, buy crypto popups #6444

### LINKED ISSUE #6444: Create on iPad when Buy Crypto button is tapped
Reproducible on f6e9db19fff852ac221463588327450d356dd6ba

Unfortunately Apple often taps on iPads :)

https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/90e268f645b53c7ea63d0eba9527af90?time=last-seven-days&versions=3.62%20(475)&deviceCategories=Tablet&sessionEventKey=4190238f27084bda8d33daa95bbaca6e_1784577745508497952

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6444

### CODE REVIEW

**Review by hboon — APPROVED** [review]

File: AlphaWallet/BuyCrypto/SelectServiceToBuyCryptoCoordinator.swift [hunk 1]
```diff
@@ -72,7 +72,8 @@ class SelectServiceToBuyCryptoCoordinator: Coordinator {
         } else if actions.count == 1 {
             completion(.service(actions[0].service))
         } else {
-            let alertController = UIAlertController(title: nil, message: .none, preferredStyle: .actionSheet)
+            let preferredStyle: UIAlertController.Style = UIDevice.current.userInterfaceIdiom == .pad ? .alert : .actionSheet
+            let alertController = UIAlertController(title: nil, message: nil, preferredStyle: preferredStyle)
```
Comment (hboon) [inline AlphaWallet/BuyCrypto/SelectServiceToBuyCryptoCoordinator.swift:76]: @oa-s Should we extract this into a short function and use it where it's needed (or not) and be easier to discover if iPads are handled correct or not? Make an issue or something if so?

**Comment by hboon** [comment]
Cherry-picked into [`v3.62-476`](https://github.com/AlphaWallet/alpha-wallet-ios/releases/tag/v3.62-476) for submission
