### PR TITLE
Fix memory leak with TransactionConfirmationViewModel #5717

### LINKED ISSUE #5717: Fix memory leak with TransactionConfirmationViewModel
objects retaining issue

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #5717

### CODE REVIEW

**Review by hboon — APPROVED** [review]

File: AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift [hunk 1]
```diff
@@ -18,8 +18,9 @@ protocol TransactionConfirmationCoordinatorDelegate: CanOpenURL, SendTransaction
 
 class TransactionConfirmationCoordinator: Coordinator {
     private let configuration: TransactionType.Configuration
-    private lazy var viewModel: TransactionConfirmationViewModel = .init(configurator: configurator, configuration: configuration, assetDefinitionStore: assetDefinitionStore, domainResolutionService: domainResolutionService, tokensService: tokensService)
+
     private lazy var rootViewController: TransactionConfirmationViewController = {
+        let viewModel = TransactionConfirmationViewModel(configurator: configurator, configuration: configuration, assetDefinitionStore: assetDefinitionStore, domainResolutionService: domainResolutionService, tokensService: tokensService)
```
Comment (hboon) [inline AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift:23]: What was leaking?

Comment (oa-s) [reply AlphaWallet/Transfer/Coordinators/TransactionConfirmationCoordinator.swift:23]: View model was capturing stores publisher that captures view model

https://github.com/AlphaWallet/alpha-wallet-ios/pull/5718/commits/986980a2d3cda102759dab1806c86554c07f00a0#:~:text=.flatMap%20%7B%20_%20in%20self.token%20%7D
