### PR TITLE
Tests broken #3865

### LINKED ISSUE #3865: Tests broken

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3865

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Good catch. This is very strange. This test passes for me on `master` / 259f0473ef1d9ae5eff7f7b148abf413dd0c85ec. Maybe it's because we have different locales, but I don't understand why.

But more importantly, can you help to check this first:

```
extension NSDecimalNumber {
    var localizedString: String {
        return self.description(withLocale: Config.locale)
    }
}
```

from: https://github.com/AlphaWallet/alpha-wallet-ios/blob/259f0473ef1d9ae5eff7f7b148abf413dd0c85ec/AlphaWallet/UI/Views/AmountTextField.swift#L617

It seems like we should use one of the formatters instead, especially after the recent refactoring and forcing of decimal and thousands separator to always be `.` and `,`. Then maybe this test can would be modified/removed.

**Comment by oa-s** [comment]
For some reasons even there was set value for `Config.locale`, it clears, and `Config.locale` appears with `<current locale>`. For example `PL` it its selected on device.

File: AlphaWallet/Foundation/Formatter.swift [hunk 1]
```diff
@@ -66,6 +66,7 @@ struct Formatter {
 
     static let `default`: NumberFormatter = {
         let formatter = NumberFormatter()
+        formatter.locale = Locale(identifier: "en_US")
```
Comment (hboon) [inline AlphaWallet/Foundation/Formatter.swift:69]: Maybe we shouldn't set it here and use one of the other formatters instead? `.shortCrypto` maybe?

Comment (oa-s) [reply AlphaWallet/Foundation/Formatter.swift]: i wasn't sure in applying Locale for `default` NumberFormatter, updated it

Comment (hboon) [reply AlphaWallet/Foundation/Formatter.swift]: I mean, can we not add this line at all?

> formatter.locale = Locale(identifier: "en_US")

since `basicNumberFormatter()` already add set it.

**Comment by oa-s** [comment]
@hboon updated `scientificAmount` formatter with setting localization manually
`formatter.locale = Locale(identifier: "en_US")`

**Review by hboon — APPROVED** [review]
