### PR TITLE
fix web image urls with whitespaces #6282

### LINKED ISSUE #6282: fix web image urls with whitespaces

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6282

### CODE REVIEW

File: modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift [hunk 1]
```diff
@@ -97,7 +97,7 @@ public enum WebImageURL: Codable, Hashable, Equatable, CustomStringConvertible {
         } else if let url = rewrittenUrl.rewriteIfIpfsOrNil, withUrlRewriting {
             self = .ipfs(url)
         } else {
-            self = .origin(rewrittenUrl)
+            self = .origin(url)
```
Comment (hboon) [inline modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift:100]: Careful to check again this, it might undo another commit you are working on?

File: modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift [hunk 2]
```diff
@@ -79,7 +79,7 @@ public enum WebImageURL: Codable, Hashable, Equatable, CustomStringConvertible {
     }
 
     public init?(string: String, withUrlRewriting: Bool = true, rewriteGoogleContentSizeUrl size: GoogleContentSize = .s750) {
-        guard let url = URL(string: string) else { return nil }
+        guard let url = URL(string: string.replacingOccurrences(of: " ", with: "%20").trimmed) else { return nil }
```
Comment (hboon) [inline modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift:82]: Maybe trim first then replace is better? — faster and I don't know what happens if there are leading or trailing space character that are converted to "%20"

**Review by hboon — APPROVED** [review]
