### PR TITLE
Fetch TokenInfoObject if _info is null, (actually object should be always there) #4776

### LINKED ISSUE #4776: Fetch TokenInfoObject if _info is null, (actually object should be always there)

### LINKED ISSUE #4782: Crashes when watching 0xAF4CCF79104F6e6e326CaB0e96e615973F0A3E3A (from scratch) (TokenObject.info.getter)
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 011FA82F-289C-42A3-BF29-8028F7943CCA
CrashReporter Key:   192F1E55-BEA3-C6C2-D63B-A7DD0728F6EA
Hardware Model:      MacBookPro18,2
Process:             AlphaWallet [59314]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/B09FC66A-6640-4D1F-87CA-1EDDC75BD47B/data/Containers/Bundle/Application/A24C90DD-DA38-4C14-9308-74509193960C/AlphaWallet.app/AlphaWallet
Identifier:          com.stormbird.alphawallet
Version:             3.42 (430)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [56823]
Coalition:           com.apple.CoreSimulator.SimDevice.B09FC66A-6640-4D1F-87CA-1EDDC75BD47B [5585]
Responsible Process: SimulatorTrampoline [645]

Date/Time:           2022-06-06 11:48:46.7901 +0800
Launch Time:         2022-06-06 11:48:46.0147 +0800
OS Version:          macOS 12.3 (21E230)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000018f6dd21c
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [59314]

Triggered by Thread:  16

Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator DYLD_INSERT_LIBRARIES=/Users/hboon/Library/Application Support/Reveal/RevealServer/RevealServer.xcframework/ios-arm64_i386_x86_64-simulator/RevealServer.framework/RevealServer DYLD_FRAMEWORK_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator
CoreSimulator 802.6 - Device: iPhone 11 (********-****-****-****-************) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 11
AlphaWallet/TokenObject.swift:31: Fatal error: Unexpectedly found nil while unwrapping an Optional value
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator DYLD_INSERT_LIBRARIES=/Users/hboon/Library/Application Support/Reveal/RevealServer/RevealServer.xcframework/ios-arm64_i386_x86_64-simulator/RevealServer.framework/RevealServer DYLD_FRAMEWORK_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator


Thread 0::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x180195f48 objc_retain + 40
1   libswiftCore.dylib            	       0x18f744988 static Dictionary._bridgeFromObjectiveCAdoptingNativeStorageOf(_:) + 56
2   libswiftFoundation.dylib      	       0x1b63eb198 specialized static Dictionary._conditionallyBridgeFromObjectiveC(_:result:) + 112
3   libswiftCore.dylib            	       0x18f979cb8 _tryCastFromClassToObjCBridgeable(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, void*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool, _ObjectiveCBridgeableWitnessTable const*, swift::TargetMetadata<swift::InProcess> const*) + 192
4   libswiftCore.dylib            	       0x18f978908 tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 2116
5   libswiftCore.dylib            	       0x18f978584 tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 1216
6   libswiftCore.dylib            	       0x18f978584 tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 1216
7   libswiftCore.dylib            	       0x18f977f90 swift_dynamicCast + 172
8   libswiftFoundation.dylib      	       0x1b64a53bc __JSONDecoder.container<A>(keyedBy:) + 424
9   libswiftFoundation.dylib      	       0x1b64a585c protocol witness for Decoder.container<A>(keyedBy:) in conformance __JSONDecoder + 20
10  libswiftCore.dylib            	       0x18f94fcb4 dispatch thunk of Decoder.container<A>(keyedBy:) + 16
11  AlphaWallet                   	       0x1012242c4 TokenEntry.init(from:) + 200
12  AlphaWallet                   	       0x101224708 protocol witness for Decodable.init(from:) in conformance TokenEntry + 24
13  libswiftCore.dylib            	       0x18f94fc50 dispatch thunk of Decodable.init(from:) + 16
14  libswiftFoundation.dylib      	       0x1b64ac768 _JSONUnkeyedDecodingContainer.decode<A>(_:) + 2016
15  libswiftFoundation.dylib      	       0x1b64ae21c protocol witness for UnkeyedDecodingContainer.decode<A>(_:) in conformance _JSONUnkeyedDecodingContainer + 12
16  libswiftCore.dylib            	       0x18f706f60 Array<A>.init(from:) + 328
17  libswiftCore.dylib            	       0x18f70701c protocol witness for Decodable.init(from:) in conformance <A> [A] + 28
18  libswiftCore.dylib            	       0x18f94fc50 dispatch thunk of Decodable.init(from:) + 16
19  libswiftFoundation.dylib      	       0x1b64b0bc4 __JSONDecoder.unbox_(_:as:) + 1144
20  libswiftFoundation.dylib      	       0x1b64a4e04 JSONDecoder.decode<A>(_:from:) + 1000
21  libswiftFoundation.dylib      	       0x1b64b1acc dispatch thunk of JSONDecoder.decode<A>(_:from:) + 20
22  AlphaWallet                   	       0x101224e70 TokenJsonReader.readAndDecodeData(fileName:) + 1104 (TokenGroupIdentifier.swift:49)
23  AlphaWallet                   	       0x10122499c TokenJsonReader.init(fromLocalFileNameWithoutSuffix:) + 104 (TokenGroupIdentifier.swift:39)
24  AlphaWallet                   	       0x101224924 TokenJsonReader.__allocating_init(fromLocalFileNameWithoutSuffix:) + 64
25  AlphaWallet                   	       0x101226170 static TokenGroupIdentifier.identifier(fromFileName:) + 108 (TokenGroupIdentifier.swift:113)
26  AlphaWallet                   	       0x1008afefc closure #1 in ActiveWalletCoordinator.tokenCollection.getter + 124 (ActiveWalletCoordinator.swift:121)
27  AlphaWallet                   	       0x10089eef4 ActiveWalletCoordinator.tokenCollection.getter + 168 (ActiveWalletCoordinator.swift:120)
28  AlphaWallet                   	       0x1008a32ac ActiveWalletCoordinator.createTokensCoordinator(promptBackupCoordinator:activitiesService:) + 540 (ActiveWalletCoordinator.swift:325)
29  AlphaWallet                   	       0x1008a3f98 ActiveWalletCoordinator.setupTabBarController() + 136 (ActiveWalletCoordinator.swift:398)
30  AlphaWallet                   	       0x1008a1270 ActiveWalletCoordinator.start(animated:) + 180 (ActiveWalletCoordinator.swift:221)
31  AlphaWallet                   	       0x100893720 AppCoordinator.showActiveWallet(for:animated:) + 1112 (AppCoordinator.swift:204)
32  AlphaWallet                   	       0x100892fe8 AppCoordinator.start() + 1160 (AppCoordinator.swift:147)
33  AlphaWallet                   	       0x10094e098 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 1936 (AppDelegate.swift:44)
34  AlphaWallet                   	       0x10094e8ec @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 196
35  UIKitCore                     	       0x184d780b4 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 252
36  UIKitCore                     	       0x184d799f4 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3452
37  UIKitCore                     	       0x184d7f22c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1100
38  UIKitCore                     	       0x18439f6dc -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 124
39  UIKitCore                     	       0x18492d03c _UIScenePerformActionsWithLifecycleActionMask + 96
40  UIKitCore                     	       0x1843a0174 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 188
41  UIKitCore                     	       0x18439fc0c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 240
42  UIKitCore                     	       0x18439ffac -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 744
43  UIKitCore                     	       0x18439f8ac -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 336
44  UIKitCore                     	       0x1843a9394 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 188
45  UIKitCore                     	       0x184821d50 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 812
46  UIKitCore                     	       0x1849462e8 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 248
47  UIKitCore                     	       0x1843a9014 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 356
48  UIKitCore                     	       0x1841c2ba4 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.578 + 744
49  UIKitCore                     	       0x1841c159c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
50  UIKitCore                     	       0x1841c2784 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 264
51  UIKitCore                     	       0x184d7dc18 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 524
52  UIKitCore                     	       0x184851128 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 360
53  FrontBoardServices            	       0x18615b718 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 412
54  FrontBoardServices            	       0x186187620 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180 + 100
55  FrontBoardServices            	       0x186169d00 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
56  FrontBoardServices            	       0x18618723c __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 312
57  libdispatch.dylib             	       0x18010ea98 _dispatch_client_callout + 16
58  libdispatch.dylib             	       0x180112268 _dispatch_block_invoke_direct + 244
59  FrontBoardServices            	       0x1861ad074 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
60  FrontBoardServices            	       0x1861acf4c -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
61  FrontBoardServices            	       0x1861ad0a4 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
62  CoreFoundation                	       0x180360820 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
63  CoreFoundation                	       0x180360720 __CFRunLoopDoSource0 + 204
64  CoreFoundation                	       0x18035fab0 __CFRunLoopDoSources0 + 256
65  CoreFoundation                	       0x18035a004 __CFRunLoopRun + 744
66  CoreFoundation                	       0x180359804 CFRunLoopRunSpecific + 572
67  GraphicsServices              	       0x18c23660c GSEventRunModal + 160
68  UIKitCore                     	       0x184d7bd2c -[UIApplication _run] + 992
69  UIKitCore                     	       0x184d808c8 UIApplicationMain + 112
70  AlphaWallet                   	       0x1009517d4 main + 64 (AppDelegate.swift:10)
71  dyld_sim                      	       0x103875cd8 start_sim + 20
72  dyld                          	       0x103a59088 start + 516

//[snipped]

Thread 16 Crashed:: org.alphawallet.swift.realmStore
0   libswiftCore.dylib            	       0x18f6dd21c closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 356
1   libswiftCore.dylib            	       0x18f6dd21c closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 356
2   libswiftCore.dylib            	       0x18f6dcf84 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 192
3   libswiftCore.dylib            	       0x18f6dc954 _assertionFailure(_:_:file:line:flags:) + 228
4   AlphaWallet                   	       0x1007dc874 TokenObject.info.getter + 200 (TokenObject.swift:31)
5   AlphaWallet                   	       0x101229fe4 Token.init(tokenObject:) + 1088 (Token.swift:93)
6   AlphaWallet                   	       0x100bbc454 closure #1 in closure #1 in MultipleChainsTokensDataStore.enabledTokens(for:) + 56 (TokensDataStore.swift:149)
7   libswiftCore.dylib            	       0x18f6cfb2c Optional.map<A>(_:) + 240
8   libswiftCore.dylib            	       0x18f7c5d04 LazyMapSequence.Iterator.next() + 244
9   libswiftCore.dylib            	       0x18f726cfc _copySequenceToContiguousArray<A>(_:) + 608
10  libswiftCore.dylib            	       0x18f8ad85c protocol witness for Sequence._copyToContiguousArray() in conformance Zip2Sequence<A, B> + 36
11  libswiftCore.dylib            	       0x18f6c04a0 Array.init<A>(_:) + 32
12  AlphaWallet                   	       0x100bbc3a4 closure #1 in MultipleChainsTokensDataStore.enabledTokens(for:) + 272 (TokensDataStore.swift:149)
13  AlphaWallet                   	       0x100f5f148 closure #1 in RealmStore.performSync(_:) + 200 (RealmStore.swift:37)
14  AlphaWallet                   	       0x100b4f2e8 RunLoopThread.execute(_:) + 808 (RunLoopThread.swift:67)
15  AlphaWallet                   	       0x100b4f378 @objc RunLoopThread.execute(_:) + 52
16  Foundation                    	       0x18084e6bc __NSThreadPerformPerform + 164
17  CoreFoundation                	       0x180360820 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
18  CoreFoundation                	       0x180360720 __CFRunLoopDoSource0 + 204
19  CoreFoundation                	       0x18035fab0 __CFRunLoopDoSources0 + 256
20  CoreFoundation                	       0x18035a004 __CFRunLoopRun + 744
21  CoreFoundation                	       0x180359804 CFRunLoopRunSpecific + 572
22  Foundation                    	       0x1808245bc -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
23  AlphaWallet                   	       0x100b4e72c closure #1 in closure #1 in RunLoopThread.main() + 172 (RunLoopThread.swift:36)
24  AlphaWallet                   	       0x100b4e778 thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 28
25  AlphaWallet                   	       0x100b50090 partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 32
26  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
27  AlphaWallet                   	       0x100b4e33c closure #1 in RunLoopThread.main() + 1072 (RunLoopThread.swift:35)
28  AlphaWallet                   	       0x100b4e7e0 thunk for @callee_guaranteed () -> (@error @owned Error) + 24
29  AlphaWallet                   	       0x100b4e83c partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) + 32
30  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
31  AlphaWallet                   	       0x100b4dee8 RunLoopThread.main() + 120 (RunLoopThread.swift:27)
32  AlphaWallet                   	       0x100b4e86c @objc RunLoopThread.main() + 36
33  Foundation                    	       0x18084e30c __NSThread__start__ + 792
34  libsystem_pthread.dylib       	       0x1cba8d6c8 _pthread_start + 116
35  libsystem_pthread.dylib       	       0x1cba88910 thread_start + 8

Thread 17:
0   libsystem_pthread.dylib       	       0x1cba888fc start_wqthread + 0


Thread 16 crashed with ARM Thread State (64-bit):
    x0: 0x0000000103b3c000   x1: 0x0000600002cee490   x2: 0x0000000000000004   x3: 0x000000018015e4f8
    x4: 0x0000000000000000   x5: 0x000000017013c600   x6: 0x0000000000000065   x7: 0x00000000000005d0
    x8: 0x00000000000000cb   x9: 0x00000000d902affb  x10: 0x00000000000007fb  x11: 0x00000000000007fd
   x12: 0x0000000000000076  x13: 0x00000000d902affb  x14: 0x00000000d922b000  x15: 0x0000000000000056
   x16: 0x0000000080000000  x17: 0x0000000059200000  x18: 0x0000000000000000  x19: 0x0000000000000003
   x20: 0x000000012d60fb70  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000017013c6b0   lr: 0x000000018f6dd21c
    sp: 0x000000017013c690   pc: 0x000000018f6dd21c cpsr: 0x60001000
   far: 0x000000014d618df0  esr: 0xf2000001 (Breakpoint) brk 1

```

### LINKED ISSUE #4783: Crashes when watching 0xbbc (from scratch) 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 05695A78-F737-48C5-9257-C6DEEE26CB51
CrashReporter Key:   192F1E55-BEA3-C6C2-D63B-A7DD0728F6EA
Hardware Model:      MacBookPro18,2
Process:             AlphaWallet [57581]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/B09FC66A-6640-4D1F-87CA-1EDDC75BD47B/data/Containers/Bundle/Application/3F09A02F-A004-461F-985F-DF996B0FEE84/AlphaWallet.app/AlphaWallet
Identifier:          com.stormbird.alphawallet
Version:             3.42 (430)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [56823]
Coalition:           com.apple.CoreSimulator.SimDevice.B09FC66A-6640-4D1F-87CA-1EDDC75BD47B [5585]
Responsible Process: SimulatorTrampoline [645]

Date/Time:           2022-06-06 11:44:32.3862 +0800
Launch Time:         2022-06-06 11:44:31.6210 +0800
OS Version:          macOS 12.3 (21E230)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  17

Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator DYLD_INSERT_LIBRARIES=/Users/hboon/Library/Application Support/Reveal/RevealServer/RevealServer.xcframework/ios-arm64_i386_x86_64-simulator/RevealServer.framework/RevealServer DYLD_FRAMEWORK_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator
CoreSimulator 802.6 - Device: iPhone 11 (********-****-****-****-************) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 11
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.'
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator DYLD_INSERT_LIBRARIES=/Users/hboon/Library/Application Support/Reveal/RevealServer/RevealServer.xcframework/ios-arm64_i386_x86_64-simulator/RevealServer.framework/RevealServer DYLD_FRAMEWORK_PATH=/Users/hboon/Library/Caches/JetBrains/AppCode2022.1/DerivedData/AlphaWallet-fhrdtxzfonlsvgdcvswlsqqysunn/Build/Products/Debug-iphonesimulator
abort() called


Last Exception Backtrace:
0   CoreFoundation                	       0x1803f25d0 __exceptionPreprocess + 216
1   libobjc.A.dylib               	       0x18019813c objc_exception_throw + 56
2   Realm                         	       0x1085ad518 RLMVerifyInWriteTransaction(RLMObjectBase*) + 160 (RLMObject_Private.hpp:58)
3   Realm                         	       0x1085bd220 (anonymous namespace)::willChange(RLMObservationTracker&, RLMObjectBase*, unsigned long) + 32 (RLMAccessor.mm:388)
4   Realm                         	       0x1085ad658 void (anonymous namespace)::kvoSetValue<RLMObjectBase* __strong, RLMObjectBase* __strong>(RLMObjectBase*, unsigned long, RLMObjectBase* __strong) + 96 (RLMAccessor.mm:400)
5   Realm                         	       0x1085ca690 invocation function for block in objc_object* (anonymous namespace)::makeSetter<RLMObjectBase* __strong, RLMObjectBase* __strong>(RLMProperty*) + 72 (RLMAccessor.mm:417)
6   AlphaWallet                   	       0x102405aa8 TokenObject.getTokenInfo() + 684 (TokenObject.swift:87)
7   AlphaWallet                   	       0x1024045ac TokenObject.info.getter + 28 (TokenObject.swift:31)
8   AlphaWallet                   	       0x102e51fb4 Token.init(tokenObject:) + 1088 (Token.swift:93)
9   AlphaWallet                   	       0x1027e444c closure #1 in closure #1 in MultipleChainsTokensDataStore.enabledTokens(for:) + 56 (TokensDataStore.swift:149)
10  libswiftCore.dylib            	       0x18f6cfb2c Optional.map<A>(_:) + 240
11  libswiftCore.dylib            	       0x18f7c5d04 LazyMapSequence.Iterator.next() + 244
12  libswiftCore.dylib            	       0x18f726cfc _copySequenceToContiguousArray<A>(_:) + 608
13  libswiftCore.dylib            	       0x18f8ad85c protocol witness for Sequence._copyToContiguousArray() in conformance Zip2Sequence<A, B> + 36
14  libswiftCore.dylib            	       0x18f6c04a0 Array.init<A>(_:) + 32
15  AlphaWallet                   	       0x1027e439c closure #1 in MultipleChainsTokensDataStore.enabledTokens(for:) + 272 (TokensDataStore.swift:149)
16  AlphaWallet                   	       0x102b87140 closure #1 in RealmStore.performSync(_:) + 200 (RealmStore.swift:37)
17  AlphaWallet                   	       0x1027772e0 RunLoopThread.execute(_:) + 808 (RunLoopThread.swift:67)
18  AlphaWallet                   	       0x102777370 @objc RunLoopThread.execute(_:) + 52
19  Foundation                    	       0x18084e6bc __NSThreadPerformPerform + 164
20  CoreFoundation                	       0x180360820 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
21  CoreFoundation                	       0x180360720 __CFRunLoopDoSource0 + 204
22  CoreFoundation                	       0x18035fab0 __CFRunLoopDoSources0 + 256
23  CoreFoundation                	       0x18035a004 __CFRunLoopRun + 744
24  CoreFoundation                	       0x180359804 CFRunLoopRunSpecific + 572
25  Foundation                    	       0x1808245bc -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
26  AlphaWallet                   	       0x102776724 closure #1 in closure #1 in RunLoopThread.main() + 172 (RunLoopThread.swift:36)
27  AlphaWallet                   	       0x102776770 thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 28
28  AlphaWallet                   	       0x102778088 partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 32
29  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
30  AlphaWallet                   	       0x102776334 closure #1 in RunLoopThread.main() + 1072 (RunLoopThread.swift:35)
31  AlphaWallet                   	       0x1027767d8 thunk for @callee_guaranteed () -> (@error @owned Error) + 24
32  AlphaWallet                   	       0x102776834 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) + 32
33  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
34  AlphaWallet                   	       0x102775ee0 RunLoopThread.main() + 120 (RunLoopThread.swift:27)
35  AlphaWallet                   	       0x102776864 @objc RunLoopThread.main() + 36
36  Foundation                    	       0x18084e30c __NSThread__start__ + 792
37  libsystem_pthread.dylib       	       0x1cba8d6c8 _pthread_start + 116
38  libsystem_pthread.dylib       	       0x1cba88910 thread_start + 8

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage


Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	       0x1cba7e820 os_unfair_lock_lock_with_options + 0
1   CoreFoundation                	       0x1802fd768 CFCharacterSetGetPredefined + 56
2   libswiftFoundation.dylib      	       0x1b65b29cc static CharacterSet.whitespaces.getter + 20
3   AlphaWallet                   	       0x10257bdbc String.trimmed.getter + 124 (String.swift:51)
4   AlphaWallet                   	       0x102e4b5f0 Contract.key.getter + 260 (TokenGroupIdentifier.swift:15)
5   AlphaWallet                   	       0x102e4d550 TokenJsonReader.tokenGroupDictionary() + 748 (TokenGroupIdentifier.swift:65)
6   AlphaWallet                   	       0x102e4e178 static TokenGroupIdentifier.identifier(fromFileName:) + 164 (TokenGroupIdentifier.swift:115)
7   AlphaWallet                   	       0x1024d7ef4 closure #1 in ActiveWalletCoordinator.tokenCollection.getter + 124 (ActiveWalletCoordinator.swift:121)
8   AlphaWallet                   	       0x1024c6eec ActiveWalletCoordinator.tokenCollection.getter + 168 (ActiveWalletCoordinator.swift:120)
9   AlphaWallet                   	       0x1024cb2a4 ActiveWalletCoordinator.createTokensCoordinator(promptBackupCoordinator:activitiesService:) + 540 (ActiveWalletCoordinator.swift:325)
10  AlphaWallet                   	       0x1024cbf90 ActiveWalletCoordinator.setupTabBarController() + 136 (ActiveWalletCoordinator.swift:398)
11  AlphaWallet                   	       0x1024c9268 ActiveWalletCoordinator.start(animated:) + 180 (ActiveWalletCoordinator.swift:221)
12  AlphaWallet                   	       0x1024bb718 AppCoordinator.showActiveWallet(for:animated:) + 1112 (AppCoordinator.swift:204)
13  AlphaWallet                   	       0x1024bafe0 AppCoordinator.start() + 1160 (AppCoordinator.swift:147)
14  AlphaWallet                   	       0x102576090 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 1936 (AppDelegate.swift:44)
15  AlphaWallet                   	       0x1025768e4 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 196
16  UIKitCore                     	       0x184d780b4 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 252
17  UIKitCore                     	       0x184d799f4 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3452
18  UIKitCore                     	       0x184d7f22c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1100
19  UIKitCore                     	       0x18439f6dc -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 124
20  UIKitCore                     	       0x18492d03c _UIScenePerformActionsWithLifecycleActionMask + 96
21  UIKitCore                     	       0x1843a0174 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 188
22  UIKitCore                     	       0x18439fc0c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 240
23  UIKitCore                     	       0x18439ffac -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 744
24  UIKitCore                     	       0x18439f8ac -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 336
25  UIKitCore                     	       0x1843a9394 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 188
26  UIKitCore                     	       0x184821d50 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 812
27  UIKitCore                     	       0x1849462e8 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 248
28  UIKitCore                     	       0x1843a9014 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 356
29  UIKitCore                     	       0x1841c2ba4 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.578 + 744
30  UIKitCore                     	       0x1841c159c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
31  UIKitCore                     	       0x1841c2784 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 264
32  UIKitCore                     	       0x184d7dc18 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 524
33  UIKitCore                     	       0x184851128 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 360
34  FrontBoardServices            	       0x18615b718 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 412
35  FrontBoardServices            	       0x186187620 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180 + 100
36  FrontBoardServices            	       0x186169d00 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
37  FrontBoardServices            	       0x18618723c __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 312
38  libdispatch.dylib             	       0x18010ea98 _dispatch_client_callout + 16
39  libdispatch.dylib             	       0x180112268 _dispatch_block_invoke_direct + 244
40  FrontBoardServices            	       0x1861ad074 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
41  FrontBoardServices            	       0x1861acf4c -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
42  FrontBoardServices            	       0x1861ad0a4 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
43  CoreFoundation                	       0x180360820 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
44  CoreFoundation                	       0x180360720 __CFRunLoopDoSource0 + 204
45  CoreFoundation                	       0x18035fab0 __CFRunLoopDoSources0 + 256
46  CoreFoundation                	       0x18035a004 __CFRunLoopRun + 744
47  CoreFoundation                	       0x180359804 CFRunLoopRunSpecific + 572
48  GraphicsServices              	       0x18c23660c GSEventRunModal + 160
49  UIKitCore                     	       0x184d7bd2c -[UIApplication _run] + 992
50  UIKitCore                     	       0x184d808c8 UIApplicationMain + 112
51  AlphaWallet                   	       0x1025797cc main + 64 (AppDelegate.swift:10)
52  dyld_sim                      	       0x105295cd8 start_sim + 20
53  dyld                          	       0x10531d088 start + 516

//[snipped]

Thread 17 Crashed:: org.alphawallet.swift.realmStore
0   libsystem_kernel.dylib        	       0x1cba39e60 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1cba8d3c0 pthread_kill + 256
2   libsystem_c.dylib             	       0x18010247c __abort + 124
3   libsystem_c.dylib             	       0x180102400 abort + 136
4   libc++abi.dylib               	       0x18023eeb4 abort_message + 128
5   libc++abi.dylib               	       0x18022f66c demangling_terminate_handler() + 300
6   libobjc.A.dylib               	       0x18017ae80 _objc_terminate() + 124
7   AlphaWallet                   	       0x102fb5400 FIRCLSTerminateHandler() + 404 (FIRCLSException.mm:327)
8   libc++abi.dylib               	       0x18023e364 std::__terminate(void (*)()) + 16
9   libc++abi.dylib               	       0x180240dc0 __cxa_rethrow + 144
10  libobjc.A.dylib               	       0x1801982d0 objc_exception_rethrow + 40
11  CoreFoundation                	       0x1803598f0 CFRunLoopRunSpecific + 808
12  Foundation                    	       0x1808245bc -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
13  AlphaWallet                   	       0x102776724 closure #1 in closure #1 in RunLoopThread.main() + 172 (RunLoopThread.swift:36)
14  AlphaWallet                   	       0x102776770 thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 28
15  AlphaWallet                   	       0x102778088 partial apply for thunk for @callee_guaranteed () -> (@unowned Bool, @error @owned Error) + 32
16  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
17  AlphaWallet                   	       0x102776334 closure #1 in RunLoopThread.main() + 1072 (RunLoopThread.swift:35)
18  AlphaWallet                   	       0x1027767d8 thunk for @callee_guaranteed () -> (@error @owned Error) + 24
19  AlphaWallet                   	       0x102776834 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) + 32
20  libswiftObjectiveC.dylib      	       0x1b6712f3c autoreleasepool<A>(invoking:) + 56
21  AlphaWallet                   	       0x102775ee0 RunLoopThread.main() + 120 (RunLoopThread.swift:27)
22  AlphaWallet                   	       0x102776864 @objc RunLoopThread.main() + 36
23  Foundation                    	       0x18084e30c __NSThread__start__ + 792
24  libsystem_pthread.dylib       	       0x1cba8d6c8 _pthread_start + 116
25  libsystem_pthread.dylib       	       0x1cba88910 thread_start + 8


Thread 17 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000989680   x6: 0x000000000000006e   x7: 0x00000000000005d0
    x8: 0x000000016e5a3000   x9: 0x9d4b0613432a4b2e  x10: 0x00000000000003e8  x11: 0x000000000000000b
   x12: 0x0000000000000000  x13: 0x0000000033222000  x14: 0x0000000000000010  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x0000000000000002  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000016e5a3000  x21: 0x0000000000006f03  x22: 0x000000016e5a30e0  x23: 0x00006000017a67e0
   x24: 0x0000000000000000  x25: 0x0000000000000001  x26: 0x0000000e89940fdf  x27: 0x00000001da35f000
   x28: 0x0000000000000001   fp: 0x000000016e5a20c0   lr: 0x00000001cba8d3c0
    sp: 0x000000016e5a20a0   pc: 0x00000001cba39e60 cpsr: 0x40001000
   far: 0x00000001cba31000  esr: 0x56000080  Address size fault
```

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4776, Closes #4783, Closes #4782

### CODE REVIEW

File: AlphaWallet/Tokens/Types/TokenObject.swift [hunk 1]
```diff
@@ -28,7 +28,7 @@ class TokenObject: Object {
     @objc dynamic var _info: TokenInfoObject?
 
     var info: TokenInfoObject {
-        get { return _info! } //NOTE: Better to make it crash than create dummy object
+        get { return getTokenInfo() } //NOTE: Better to make it crash than create dummy object
```
Comment (hboon) [inline AlphaWallet/Tokens/Types/TokenObject.swift:31]: Should we remove the comment?

**Review by hboon — APPROVED** [review]

File: AlphaWallet/Tokens/Types/TokenObject.swift (hunk 1 above)
Comment (oa-s) [reply AlphaWallet/Tokens/Types/TokenObject.swift:31]: Yes, I will do it. Also found the reason of it, TolenUpdate, I missed to instantiate info there. 🤦‍♂️

**Comment by hboon** [comment]
@oa-s maybe this fixes #4782 ?

**Comment by oa-s** [comment]
> @oa-s maybe this fixes #4782 ?

checking

**Comment by oa-s** [comment]
@hboon can you check if its still reproducible for you?

**Comment by hboon** [comment]
@oa-s Not reproducible anymore
