### PR TITLE
Split Etherscan and Blockscout on two independent networkings #6792

### LINKED ISSUE #6792: Split Etherscan and Blockscout on two independent networkings
`Blockscout` ignores params: `startblock`, `endblock`, and wants them to be `start_block`, `end_block`, so existed pagination doesn't work for `Blockscout`.

docs: https://explorer.palm-uat.xyz/api-docs#account

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6792

### CODE REVIEW

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/GetTransactionsRequest.swift [hunk 1]
```diff
@@ -8,44 +8,12 @@
...
-    struct NoBlockchainExplorerApi: Error {
-    }
-
-    let server: RPCServer
-    let address: AlphaWallet.Address
-    let startBlock: Int
-    let endBlock: Int
-    let sortOrder: SortOrder
-
     public enum SortOrder: String {
```
Comment (hboon) [inline modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/GetTransactionsRequest.swift:11]: Seems like we don't need `GetTransactions` anymore. If we want to keep the PR smaller, can just remove `asURLRequest()` and make `GetTransactions` no longer conform to `URLRequestConvertible`?

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift [hunk 2]
```diff
@@ -0,0 +1,318 @@
...
+            .tryMap { UniqueNonEmptyContracts(json: try JSON(data: $0.data), tokenType: .erc20) }
+            .mapError { PromiseError.some(error: $0) }
+            .print("xxx.blockscout.normalTransactions.server: \(server)")
+            .eraseToAnyPublisher()
+    }
+
+    func erc721TokenInteractions(walletAddress: AlphaWallet.Address,
+                                 startBlock: Int?) -> AnyPublisher<UniqueNonEmptyContracts, PromiseError> {
+
+        switch server {
```
Comment (hboon) [inline modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift:58]: Is this switch for logging the same for all cases in both `EtherscanCompatibleApiNetworking` and `BlockscoutApiNetworking`? Maybe useful to extract it out into an extension of `ApiNetworking`? Should be useful to keep it around and still log it with `debugLog()` and even crash with `precondition()`

**Review by hboon — COMMENTED** [review]
Seems OK

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/GetTransactionsRequest.swift (hunk 1 above)
Comment (oa-s) [reply modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/Types/GetTransactionsRequest.swift:11]: yes, i will remove it in another pr, to avoid conflicts for now

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift (hunk 2 above)
Comment (oa-s) [reply modules/AlphaWalletFoundation/AlphaWalletFoundation/Transactions/BlockscoutApiNetworking.swift:58]: its a bit different for eip 1155
