### PR TITLE
move mapping tokens uri to Json From TokenUri, and make calls synchronized #6678

### LINKED ISSUE #6678: Crash on the simulator at `URLComponents(url: uri, resolvingAgainstBaseURL: false)`
Got this crash on the simulator at `URLComponents(url: uri, resolvingAgainstBaseURL: false)`, but not sure why because `uri` is supposed to be a non-optional `URL`:

```
2023-04-13 09:14:40.481556+0800 AlphaWallet[51793:666253] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   Foundation                          0x0000000180bfc7b4 -[__NSConcreteURLComponents initWithURL:resolvingAgainstBaseURL:] + 276
	3   Foundation                          0x00000001809149c4 $s10Foundation13URLComponentsV3url23resolvingAgainstBaseURLACSgAA0G0Vh_SbtcfC + 60
	4   AlphaWalletFoundation               0x000000010946cfdc $s21AlphaWalletFoundation23HostBasedTokenUriMapperV3map3uri0C03URLVSgAH_tF + 512
	5   AlphaWalletFoundation               0x000000010946de64 $s21AlphaWalletFoundation23HostBasedTokenUriMapperVAA0fG14MapSupportableA2aDP3map3uri0C03URLVSgAJ_tFTW + 20
	6   AlphaWalletFoundation               0x000000010946cc14 $s21AlphaWalletFoundation14TokenUriMapperV3map3uri0C03URLVSgAH_tFAiA0dE14MapSupportable_pXEfU_ + 96
	7   AlphaWalletFoundation               0x000000010946cc40 $s21AlphaWalletFoundation14TokenUriMapperV3map3uri0C03URLVSgAH_tFAiA0dE14MapSupportable_pXEfU_TA + 24
	8   libswiftCore.dylib                  0x000000018be8fd88 $sSTsE10compactMapySayqd__Gqd__Sg7ElementQzKXEKlF + 696
	9   AlphaWalletFoundation               0x000000010946cb2c $s21AlphaWalletFoundation14TokenUriMapperV3map3uri0C03URLVSgAH_tF + 224
	10  AlphaWalletFoundation               0x000000010946ccec $s21AlphaWalletFoundation14TokenUriMapperVAA0dE14MapSupportableA2aDP3map3uri0C03URLVSgAJ_tFTW + 16
	11  AlphaWalletFoundation               0x0000000109249a14 $s21AlphaWalletFoundation19NonFungibleContractC013getUriOrTokenH03for8contract7Combine12AnyPublisherVyAA0jH4DataO6APIKit16SessionTaskErrorOGSS_0aB7Address0aB0O0U0OtFA2KcfU0_ + 584
	12  AlphaWalletFoundation               0x0000000109249b54 $s21AlphaWalletFoundation19NonFungibleContractC013getUriOrTokenH03for8contract7Combine12AnyPublisherVyAA0jH4DataO6APIKit16SessionTaskErrorOGSS_0aB7Address0aB0O0U0OtFA2KcfU0_TA + 16
```

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6678

### CODE REVIEW

**Review by hboon — APPROVED** [review]
How did you make the calls synchronized?

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift [hunk 1]
```diff
@@ -23,6 +23,7 @@ final class JsonFromTokenUri {
     private let queue = DispatchQueue(label: "org.alphawallet.swift.jsonFromTokenUri")
```
Comment (oa-s) [inline modules/AlphaWalletFoundation/AlphaWalletFoundation/Tokens/Helpers/JsonFromTokenUri.swift:23]: JsonFromTokenUri is thread safe, all calls perform on `queue`, so we just moved uri mapped to be called of that queue
