### PR TITLE
Fixed UIButton setBackgroundColor darkMode bug

### LINKED ISSUE #4986: Background color for selected segment broken
Screenshot 2022-07-14 at 09 27 04

### LINKED ISSUE #4995: Foreground color of "1D" label of charts is broken
It appears if we tap and hold it:

Screenshot 2022-07-18 at 2 48 40 PM

Probably broken by work on Dark Mode

### PR DESCRIPTION
**Pull request by eviltofu**
Fixes #4995 Fixes #4986

image

### CODE REVIEW

File: AlphaWallet/Extensions/UIColor.swift [hunk 1]
```diff
@@ -44,4 +44,7 @@ extension UIColor {
         return resolvedColor(with: UITraitCollection(userInterfaceStyle: .dark))
     }
 
+    var isDynamic: Bool {
+        return lightMode != darkMode
```
Comment (hboon) [inline AlphaWallet/Extensions/UIColor.swift:48]: Is there a better way to achieve this?

**Review by hboon — APPROVED** [review]
