### PR TITLE
Fix AccountsViewController memory leaks #3672

### LINKED ISSUE #3672: Fix `AccountsViewController` memory leaks
While closing opened AccountsViewController from setting, it doesn't get deleted

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3672

### CODE REVIEW

File: AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift [hunk 1]
```diff
@@ -186,7 +186,7 @@ class WalletBalanceCoordinator: NSObject, WalletBalanceCoordinatorType {
     }
 
     private func notifyWalletSummary() {
-        walletSummary.done(on: queue, { [weak self] summary in
+        walletSummary.done(on: .main, { [weak self] summary in
```
Comment (hboon) [inline AlphaWallet/Core/Coordinators/WalletBalance/WalletBalanceCoordinator.swift:189]: Doesn't need `.main` since that's the default for PromiseKit, right? But we should reduce our usage of custom queues anyway. Would you modify and then merge?

**Review by hboon — APPROVED** [review]
