### PR TITLE
Make settings view model subscribable, add reload view model when wallet name or ens resolved, fixes assigning resolved ens name to wrong cell, for settings screen #4903

### LINKED ISSUE #4903: A Temporary Displaying Issue on Settings
Have you noticed a displaying issue loading Settings when you open AlphaWallet? For a moment the page does not displayed SELECT ACTIVE Networks and instead displayed repeatedly CHANGE/ADD WALLET. 

image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4903

### CODE REVIEW

File: AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift [hunk 1]
```diff
@@ -41,7 +41,8 @@ class SettingsCoordinator: Coordinator {
 	var coordinators: [Coordinator] = []
 
 	lazy var rootViewController: SettingsViewController = {
-		let controller = SettingsViewController(config: config, keystore: keystore, account: account, analyticsCoordinator: analyticsCoordinator, domainResolutionService: domainResolutionService)
+        let viewModel = SettingsViewModel(account: account, keystore: keystore, config: config, analyticsCoordinator: analyticsCoordinator, domainResolutionService: domainResolutionService)
+		let controller = SettingsViewController(viewModel: viewModel)
```
Comment (hboon) [inline AlphaWallet/Settings/Coordinators/SettingsCoordinator.swift:45]: Indentation seems to be off here.

File: AlphaWallet/Settings/ViewControllers/SettingsViewController.swift [hunk 2]
```diff
@@ -1,7 +1,7 @@
 // Copyright © 2018 Stormbird PTE. LTD.
 
 import UIKit
-import PromiseKit
+import Combine
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/SettingsViewController.swift:4]: There seems to be quite a bit of unrelated changes in the PR. Are all of them needed to fix it?

Can you also rename the PR title and commit? The original issue title doesn't describe well what was the problem.

**Review by hboon — CHANGES_REQUESTED** [review]

File: AlphaWallet/Settings/ViewModels/SettingsViewModel.swift [hunk 3]
```diff
@@ -203,3 +375,22 @@ enum SettingsSection {
         }
     }
 }
+
+extension SettingsSection: Hashable {
+    static func == (lhs: SettingsSection, rhs: SettingsSection) -> Bool {
```
Comment (hboon) [inline AlphaWallet/Settings/ViewModels/SettingsViewModel.swift:380]: Think this is not necessary and can be auto-synthesized. (also the `default:` can introduce bugs when we add new cases and the compiler can't remind us to update the `==` function). Probably the other `==` function(s) too?

**Review by hboon — APPROVED** [review]
Merge when ready

**Comment by hboon** [comment]
Should also mention fixing the display/refresh bug in commit :)
