### PR TITLE
Fix displaying gasLimit error when configuring transaction #6074

### LINKED ISSUE #6074: Fix displaying gas Limit error when configuring transaction

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6074

### CODE REVIEW

**Comment by oa-s** [comment]
| Before PR | After PR |
| ------ | ------ |
|  |  |

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasLimitWarning.swift [hunk 1]
```diff
@@ -10,9 +10,6 @@ import Foundation
 extension TransactionConfigurator {
     public enum GasLimitWarning {
         case tooHighCustomGasLimit
-
```
Comment (hboon) [inline modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasLimitWarning.swift:13]: This is strange. Why does it not work?

Comment (oa-s) [reply modules/AlphaWalletFoundation/AlphaWalletFoundation/Transfer/Types/GasLimitWarning.swift:13]: Have no idea, maybe it's because it was defined in foundation pod, different namespaces.

**Review by hboon — APPROVED** [review]
