### PR TITLE
Remove warnings #3983

### LINKED ISSUE #3983: Remove warnings
`'unarchiveObject(with:)' was deprecated in iOS 12.0: Use +unarchivedObjectOfClass:fromData:error: instead`

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3983

### CODE REVIEW

File: AlphaWallet/Core/Device.swift [hunk 1]
```diff
@@ -180,7 +180,19 @@ public extension AlphaWallet {
 extension AlphaWallet.Device {
     /// Return `true` for landscape interface orientation
     static public var isLandscape: Bool {
-        return UIApplication.shared.statusBarOrientation == .landscapeLeft || UIApplication.shared.statusBarOrientation == .landscapeRight
+        let statusBarOrientation: UIInterfaceOrientation
+
+        if #available(iOS 13, *) {
```
Comment (hboon) [inline AlphaWallet/Core/Device.swift:185]: Our deployment target is iOS 13, so we can skip the check.

**Review by hboon — APPROVED** [review]
Merge when ready
