### PR TITLE
Fixed UIColorExtensionTests.swift

### LINKED ISSUE #5909: Test for color/UI fails
`UIColorExtensionTests.testLightDarkColorMode`

### PR DESCRIPTION
**Pull request by eviltofu**
Fixes #5909

### CODE REVIEW

File: AlphaWalletTests/Extensions/UIColorExtensionTests.swift [hunk 1]
```diff
@@ -41,8 +41,8 @@ class UIColorExtensionTests: XCTestCase {
     }
 
     func testLightDarkColorMode() throws {
-        let lightColor = Colors.appRed
-        let darkColor = Colors.appWhite
+        let lightColor = UIColor.red
```
Comment (hboon) [inline AlphaWalletTests/Extensions/UIColorExtensionTests.swift:44]: Why does the original version not work? It seems like it should work with any pair of 2 different colors?

Comment (hboon) [reply AlphaWalletTests/Extensions/UIColorExtensionTests.swift:44]: How about a different pair of arbitrary RGB colors that is not any of the semantic colors used in the app that passes? Eg 50, 100, 150 and another one? Helps show that it doesn’t rely on any style semantics

**Review by oa-s — APPROVED** [review]

File: AlphaWalletTests/Extensions/UIColorExtensionTests.swift (hunk 1 above)
Comment (eviltofu) [reply AlphaWalletTests/Extensions/UIColorExtensionTests.swift]: Ok I used 1,0,0,1 for red and 1,1,1,1 for white.
