### PR TITLE
Fix encoding missing gasPrice for swap response #6072

### LINKED ISSUE #6072: Fix encoding missing gaslimit for swap response
sometimes response contains nil for gaslimit field

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6072

### CODE REVIEW

File: AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift [hunk 1]
```diff
@@ -48,7 +48,7 @@ final class SwapQuoteDetailsViewModel {
                             type: step.type,
                             amount: pair.swapQuote.unsignedSwapTransaction.value,
                             amountUsd: pair.swapQuote.action.fromToken.priceUSD,
-                            estimate: pair.swapQuote.unsignedSwapTransaction.gasPrice ?? .zero,
+                            estimate: pair.swapQuote.unsignedSwapTransaction.gasPrice,
```
Comment (hboon) [inline AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift:51]: I didn't test this, what would happen when the `gasPrice` is missing from the swap response with this change?

Maybe we should check with the li.fi folks too (but still good to have a fix ourselves)

Comment (oa-s) [reply AlphaWallet/Swap/Swap/ViewModels/SwapQuoteDetailsViewModel.swift:51]: it just displays an error when fetching swap routes, i have no idea why it happens, something with api i suppose, because one request (eth-> usdt swap ) returns an error an the next same request returns sucessfull response.
