### PR TITLE
Move wallet name storage to json file #4733

### LINKED ISSUE #4733: Wallet Names Disappeared
The names given to my wallet addresses disappeared as if someone had erased them.

In the screenshot example you will see one of them renamed after this crash. 

image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4733

### CODE REVIEW

File: AlphaWallet/Core/Helpers/WalletStorage.swift [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+class FileWalletStorage: WalletStorage {
+    private let storage: Storage<[AlphaWallet.Address: String]>
+
+    init(config: Config = .init()) {
+        storage = .init(fileName: "wallet_names", defaultValue: [:])
+
+        //NOTE: migrate old names from user defaults to file storage
+        if !config.walletNames.isEmpty {
```
Comment (hboon) [inline AlphaWallet/Core/Helpers/WalletStorage.swift:23]: Better to separate out the migration code?

**Review by hboon — APPROVED** [review]
