### PR TITLE
Fix crash on update activity #4413

### LINKED ISSUE #4413: Fix crash on update activity

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #4413

### CODE REVIEW

File: AlphaWallet/Activities/ActivitiesService.swift [hunk 1]
```diff
@@ -427,11 +427,15 @@ class ActivitiesService: NSObject, ActivitiesServiceType {
...
             //Ugly, but should be safe
-            executeThreadSafe({ [unowned self] in
-                self.activities[index] = updatedActivity
-                self.reloadViewController(reloadImmediately: false)
-
-                self.subscribableUpdatedActivity.value = updatedActivity
+            executeThreadSafe({ [weak self] in
+                guard let strongSelf = self else { return }
+                
+                if strongSelf.activities.indices.contains(index) {
```
Comment (hboon) [inline AlphaWallet/Activities/ActivitiesService.swift:433]: Doesn't this check here and a few lines above imply that the index here and above could be wrong?

**Review by hboon — APPROVED** [review]
