### PR TITLE
Let users add a custom chain #2826

### LINKED ISSUE #2826: Let users add a custom chain
**Describe the issue**
Let users add a custom RPC, similar to MetaMask

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. Open Settings
2. Go to Select Active Networks
3. Click + button
4. Enter Data

Zeplin:
https://zpl.io/aMw5nmz

Screenshot 2021-05-31 at 14 09 51

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2826

### CODE REVIEW

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+        symbolTextField.label.text = viewModel.symbolTitle
+        blockExplorerURLTextField.label.text = viewModel.blockExplorerURLTitle
+
+        buttonsBar.buttons[0].setTitle(viewModel.saverpcServerTitle, for: .normal)
+    }
+
+    private func validateInputs() -> Bool {
+        var isValid: Bool = true
+
+        if networkNameTextField.value.isEmpty {
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:200]: Need to trim for spaces first.

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+            isValid = false
+            networkNameTextField.status = .error(R.string.localizable.addrpcServerNetworkNameError())
+        } else {
+            networkNameTextField.status = .none
+        }
+
+        if URL(string: rpcUrlTextField.value) == nil {
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:207]: This wouldn't work because `URL(string: "x")` creates a `URL` instance

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift (hunk 1 above)
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:200]: Need to trim for spaces first.

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+            isValid = false
+            rpcUrlTextField.status = .error(R.string.localizable.addrpcServerRpcUrlError())
+        } else {
+            rpcUrlTextField.status = .none
+        }
+
+        if Int(chainIDTextField.value) == nil {
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:214]: Needs to check for negative and 0.

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+        }
+
+        if symbolTextField.value.isEmpty {
+            isValid = false
+            symbolTextField.status = .error(R.string.localizable.addrpcServerSymbolError())
+        } else {
+            symbolTextField.status = .none
+        }
+
+        if URL(string: blockExplorerURLTextField.value) == nil {
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:228]: Yeah, let's let this be mandatory for now, although it can be optional strictly speaking and see if users feedback.

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift (hunk 3 above)
Comment (hboon) [reply AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:214]: We also shouldn't let users add if it is already in the list of RPCServers we ship or any custom ones they have added.

File: AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift [hunk 5]
```diff
@@ -0,0 +1,276 @@
...
+        guard validateInputs() else { return }
+
+        let customRPC = CustomRPC(
+            chainID: Int(chainIDTextField.value)!,
+            nativeCryptoTokenName: nil,
+            chainName: networkNameTextField.value,
+            symbol: symbolTextField.value,
+            rpcEndpoint: rpcUrlTextField.value,
+            explorerEndpoint: blockExplorerURLTextField.value,
+            etherscanCompatibleType: .unknown,
```
Comment (hboon) [inline AlphaWallet/Settings/ViewControllers/AddRPCServerViewController.swift:248]: Remember to determine if `.etherscan` or `.blockscout`.

**Review by hboon — COMMENTED** [review]
Looks good!

While working on #2879, I have added a mechanism to trigger the restart of the app after adding a server in my private branch so you can ignore that for now.

Are you going to work on saving the list of custom servers somewhere? Then I'll try to put that into my PR (I'm only storing it in memory during development), clean it up and we should be able to update this PR to do the app restart too.

**Comment by hboon** [comment]
@vladyslav-iosdev my bad for not finishing up my part in #2879 yet. Is it ok if I take over this PR? I think you have finished the bulk of it and really only needs to integrate with part of mine.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev my bad for not finishing up my part in #2879 yet. Is it ok if I take over this PR? I think you have finished the bulk of it and really only needs to integrate with part of mine.

Sure, go ahead. ;)

**Comment by hboon** [comment]
Contains commits from #2907 

- [ ] Merge after #2907

**Comment by hboon** [comment]
@vladyslav-iosdev done. See if it works for you. Sample chain. You'll need to disable Heco in the code so this can be added:

```
"blockExplorerUrls" : "https://hecoinfo.com"
"chainId" : "0x80"
"rpcUrls" : "https://http-mainnet-node.huobichain.com"
```

**Comment by hboon** [comment]
Rebased master.

**Comment by hboon** [comment]
@vladyslav-iosdev bump. in case you missed this.
