### PR TITLE
move to default comparison implementation for structs for `WalletBalance` #6247

### LINKED ISSUE #6247: Fix crash when updating accounts screen
```
Fatal Exception: NSInternalInconsistencyException
Diffable data source detected item identifiers that are equal but have different hash values. Two identifiers which compare as equal must return the same hash value. You must fix this in the Hashable (Swift) or hash property (Objective-C) implementation for the type of these identifiers. Identifiers that are equal but have different hash values: (AlphaWallet.AccountsViewModel.ViewModelType.wallet(AlphaWallet.AccountViewModel(displayBalanceApprecation: true, current: Optional(.real(0xE1bC6653C0259D250430e61f2c6ff924381E7134)), accountRowViewModel: AlphaWallet.AccountsViewModel.AccountRowViewModel(wallet: .real(0x0f2B8dE6E81D8504E19Fb4EB1C15Ecc2C0AE3903), blockie: AlphaWalletFoundation.BlockiesImage.image(image: <UIImage:0x281caabe0 anonymous {64, 64} renderingMode=automatic(original)>, isEnsAvatar: false), addressOrEnsName: "0x0f2B8dE6E81D8504E19Fb4EB1C15Ecc2C0AE3903", balance: AlphaWalletFoundation.WalletBalance(etherToken: Optional(AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x0000000000000000000000000000000000000000, symbol: "ETH", decimals: 18, server: AlphaWalletFoundation.RPCServer.main, type: AlphaWalletFoundation.TokenType.nativeCryptocurrency, name: "Ethereum", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(amountFull: "0", amountShort: "0", symbol: "ETH", valueDecimal: 0, amountInFiat: Optional(0.0), value: 0, balance: [], ticker: Optional(AlphaWalletFoundation.CoinTicker(primaryKey: "ethereum-USD", id: "ethereum", currency: AlphaWalletFoundation.Currency.USD, lastUpdatedAt: 2023-01-27 17:15:19 +0000, symbol: "eth", price_usd: 1591.15, percent_change_24h: -0.21387, market_cap: Optional(191583152058.0), market_cap_rank: Optional(2.0), total_volume: Optional(8887452918.0), high_24h: Optional(1609.11), low_24h: Optional(1563.06), market_cap_change_24h: Optional(-569521301.358429), market_cap_change_percentage_24h: Optional(-0.29639), circulating_supply: Optional(120516618.402028), total_supply: Optional(120516618.402028), max_supply: nil, ath: Optional(4878.
```

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6247

### CODE REVIEW

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift [hunk 1]
```diff
@@ -75,11 +75,7 @@ extension Balance: CustomStringConvertible {
     }
 }
 
-extension WalletBalance: Hashable {
-    public static func == (lhs: WalletBalance, rhs: WalletBalance) -> Bool {
-        return lhs.wallet.address == rhs.wallet.address && lhs.totalAmount == rhs.totalAmount && lhs.change == rhs.change
-    }
-}
+extension WalletBalance: Hashable { }
```
Comment (hboon) [inline modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift:78]: It would then compare `etherToken` too though. Is it ever different?

**Review by hboon — APPROVED** [review]

File: modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift (hunk 1 above)
Comment (oa-s) [reply modules/AlphaWalletFoundation/AlphaWalletFoundation/Types/WalletBalance.swift:78]: yes it will, i don't remember why it was skipped, guess for some prev logic (before adding dataStore),  but for now we need default impl of == operator for struct
